[book]
authors = ["Jason Yuan"]
language = "en"
multilingual = false
src = "src"
title = "Jason's Notebook"
description = "Rough and ready notes on various topics."
no-number = true

[build]
build-dir = "../dist/notes"

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
no-section-label = true
mathjax-support = true
site-url = "https://jasonyuan.net/notes/"
git-repository-url = "https://github.com/JasonYuan869/JasonYuan869.github.io/"