name: Build Site

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic-release   # Need an `id` for output variables

      - name: Build
        if: steps.semantic-release.outputs.new_release_published
        run: npm run build

      - name: Setup Pages
        if: steps.semantic-release.outputs.new_release_published
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: steps.semantic-release.outputs.new_release_published
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

      - name: Deploy to GitHub Pages
        if: steps.semantic-release.outputs.new_release_published
        id: deployment
        uses: actions/deploy-pages@v4
